CHANGELOG.md, GuaranteedRate.Examples.FieldUtils/GuaranteedRate.Examples.FieldUtils.csproj, GuaranteedRate.Examples.FieldUtils/packages.config, GuaranteedRate.Examples.LoanDataUtils/GuaranteedRate.Examples.LoanDataUtils.csproj, GuaranteedRate.Examples.LoanDataUtils/packages.config, GuaranteedRate.Examples.ReportingUtils/GuaranteedRate.Examples.ReportingUtils.csproj, GuaranteedRate.Examples.ReportingUtils/packages.config, GuaranteedRate.Examples.UserUtils/GuaranteedRate.Examples.UserUtils.csproj, GuaranteedRate.Examples.UserUtils/packages.config, GuaranteedRate.Sextant/EncompassUtils/LoanDataUtils.cs, GuaranteedRate.Sextant/GuaranteedRate.Sextant.csproj, GuaranteedRate.Sextant/Properties/AssemblyInfo.cs, GuaranteedRate.Sextant/packages.config, GuaranteedRate.Util.IndexFields/GuaranteedRate.Util.IndexFields.csproj, GuaranteedRate.Util.IndexFields/packages.config
1. Switched back to the full sdk, console apps had problems without it
2. In GuaranteedRate.Sextant/EncompassUtils/LoanDataUtils.cs there was a copy/paste error which caused an object to be cast wrong
=> 2 bugfixes

GuaranteedRate.Sextant/Metrics/IDataDogReporter.cs, GuaranteedRate.Sextant/Properties/AssemblyInfo.cs
I want to have my clients use the interface so we can have a Mock<IDataDogReporter> in our test code.
=> make IDataDogReporter public so clients can do dependency injection.

CHANGELOG.md, GuaranteedRate.Sextant/EncompassUtils/LoanDataUtils.cs, GuaranteedRate.Sextant/Properties/AssemblyInfo.cs
We've had a periodic problem with data getting saved across environments.  I've added a Blacklist to Peck that will reject loans with a `SessionSmartClientId` from the wrong environment.
This update to Sextant will add the server signature to loan data so that the blacklist will work.
@KseniaLaney @brianbegygr @MaxReznik @antonmos @ncapetillo-gr @KirillMedvedevGR
=> Server sig

CHANGELOG.md, GuaranteedRate.Sextant/EncompassUtils/FieldUtils.cs, GuaranteedRate.Sextant/EncompassUtils/LoanDataUtils.cs, GuaranteedRate.Sextant/Properties/AssemblyInfo.cs
-trimming field ids prior to lookup
-checking if a key exists in a dictionary before pushing to it or overwriting it
=> Forcing trimming on FieldIds before lookup

CHANGELOG.md, GuaranteedRate.Sextant/Config/IJsonEncompassConfig.cs, GuaranteedRate.Sextant/Config/JsonEncompassConfig.cs, GuaranteedRate.Sextant/GuaranteedRate.Sextant.csproj
IJsonEncompassConfig is needed if you want to ensure that the consuming class is being passed a JsonEncompassConfig.
=> add IJsonEncompassConfig

CHANGELOG.md, GuaranteedRate.Sextant/Config/IJsonEncompassConfig.cs, GuaranteedRate.Sextant/Config/JsonEncompassConfig.cs, GuaranteedRate.SextantTests/Config/JsonEncompassConfigTests.cs, GuaranteedRate.SextantTests/Config/TestJson.json, GuaranteedRate.SextantTests/Config/WindowModel.cs, GuaranteedRate.SextantTests/GuaranteedRate.SextantTests.csproj, GuaranteedRate.SextantTests/packages.config
This will allow for embedding entire object graphs in a JSON config.  Most notably, this will do away with the need to hack array values into a pipe delimited string.
=> support T GetValue<T>(string key, T defaultValue = default(T))

CHANGELOG.md, GuaranteedRate.Sextant/EncompassUtils/LoanDataUtils.cs, GuaranteedRate.Sextant/Properties/AssemblyInfo.cs
UPDATE: All fields are initially pulled in and set to an empty string value.  When the defensive ifs were removed null values were set over the default empty string.
***line 487***
I want to dive into why these if blocks were removed.  @jeffpsherman recommended removal and I believe it was due to not needing a check because of upstream filtering, but I want to confirm.
related commit : 
https://github.com/Guaranteed-Rate/GuaranteedRate.Sextant/commit/543d07fc13a805eb204a1e06b7634f1e050867f6
-------------
***line 619***
I assume this if block was removed for the same reason however my commit comment at the time was not ideal.
related commit:
https://github.com/Guaranteed-Rate/GuaranteedRate.Sextant/commit/fdc70ece01759a1fa856c1f98cc6b9c5e00ef2f
=> Adding back defensive if braces to prevent null value set by default

CHANGELOG.md, GuaranteedRate.Sextant/EncompassUtils/SessionUtils.cs, GuaranteedRate.Sextant/Properties/AssemblyInfo.cs
Encompass expects string interpretations of Guids to be wrapped in braces.  Safe checking for this as Guid.ToString() will emit a guid that does not follow this standard.
=> Armoring Loan OpenLoan(Session session, string guid)

CHANGELOG.md, GuaranteedRate.Examples.FieldUtils/GuaranteedRate.Examples.FieldUtils.csproj, GuaranteedRate.Examples.FieldUtils/app.config, GuaranteedRate.Examples.FieldUtils/packages.config, GuaranteedRate.Examples.LoanDataUtils/GuaranteedRate.Examples.LoanDataUtils.csproj, GuaranteedRate.Examples.LoanDataUtils/app.config, GuaranteedRate.Examples.LoanDataUtils/packages.config, GuaranteedRate.Examples.ReportingUtils/GuaranteedRate.Examples.ReportingUtils.csproj, GuaranteedRate.Examples.ReportingUtils/app.config, GuaranteedRate.Examples.ReportingUtils/packages.config, GuaranteedRate.Examples.UserUtils/App.config, GuaranteedRate.Examples.UserUtils/GuaranteedRate.Examples.UserUtils.csproj, GuaranteedRate.Examples.UserUtils/packages.config, GuaranteedRate.Sextant.Integration.Tests/app.config, GuaranteedRate.Sextant.Tests/GuaranteedRate.Sextant.Tests.csproj, GuaranteedRate.Sextant/GuaranteedRate.Sextant.csproj, GuaranteedRate.Sextant/Metrics/Graphite/StatsDGraphiteReport.cs, GuaranteedRate.Sextant/Metrics/SimpleMetrics.cs, GuaranteedRate.Sextant/Metrics/StatsDMetrics.cs, GuaranteedRate.Sextant/Properties/AssemblyInfo.cs, GuaranteedRate.Sextant/app.config, GuaranteedRate.Sextant/packages.config, GuaranteedRate.Util.IndexFields/App.config, GuaranteedRate.Util.IndexFields/GuaranteedRate.Util.IndexFields.csproj, GuaranteedRate.Util.IndexFields/packages.config, LoggingTestRig/App.config, LoggingTestRig/LoggingTestRig.csproj, LoggingTestRig/Program.cs, LoggingTestRig/packages.config, README.md
> This release intruduces the concept of StatsD driven metrics tracking.  We are leveraging [Metrics.NET](https://github.com/Recognos/Metrics.NET)
to backbone the effort of transposing metrics into StatsD compliant metrics for consumption by our third party reporters.  
We have elected to supoort Graphite with the `GraphiteReporter` from [Metrics.NET.Graphite](https://github.com/Recognos/Metrics.NET.Graphite) and
Datadog with the `DatadogReporter` from  [Metrics.NET.Datadog](https://github.com/danzel/Metrics.NET.Datadog)
* **Add** - `SimpleMetrics` and `StatsDMetrics` as available Metrics trackers
* **Update** - Sextant has been rolled up to .NET 4.5.2 to utilize Metrics.NET 
```csharp
[GuaranteedRate.Sextant "17.2.2.0"]
```
=> Add StatsD metrics

CHANGELOG.md, GuaranteedRate.Sextant/Logging/Loggly/LogglyLogAppender.cs, GuaranteedRate.Sextant/Properties/AssemblyInfo.cs, GuaranteedRate.Sextant/WebClients/AsyncEventReporter.cs, GuaranteedRate.Sextant/WebClients/SecureAsyncEventReporter.cs
* **Fix** - Bugfix to throw a meaningful exception if an `AsyncEventReporter` has been created without a base url
* **Fix** - Bugfix to correctly look for `LogglyLogAppender.Tags` in configuration files for the `LogglyLogAppender`
* **Fix** - Correct regression that was preventing `SecureAsyncEventReporter` from settings it's authorization header
```csharp
[GuaranteedRate.Sextant "17.2.2.1"]
```
=> Bugfix to throw a meaningful exception if an `AsyncEventReporter` does not have a base url

.gitignore, GuaranteedRate.Sextant.CustomFieldComparer/FieldExtractor.cs, GuaranteedRate.Sextant.CustomFieldComparer/GuaranteedRate.Sextant.CustomFieldComparer.csproj, GuaranteedRate.Sextant.CustomFieldComparer/Program.cs, README.md
Building on @brianbegygr 's work, some refactoring and adding reportable fields.
Next version should merge the two attribute groups into a single export
*AND* it should produce a consolidated, sorted, file/environment so that we can diff the fields using a tool like `diff`
@brianbegygr @jongear
=> Include reportable fields when diff'ing Encompass Environments

GuaranteedRate.Sextant.CustomFieldComparer/FieldExtractor.cs, GuaranteedRate.Sextant.CustomFieldComparer/FullFieldDescription.cs, GuaranteedRate.Sextant.CustomFieldComparer/GuaranteedRate.Sextant.CustomFieldComparer.csproj, GuaranteedRate.Sextant.CustomFieldComparer/Program.cs, GuaranteedRate.Sextant.CustomFieldComparer/encompass-config/dev.json
Inching forward - this version adds a sorted array of field descriptions as a single file, which should make it easier to track differences with something like `diff`
Also adds reportable field tracking inside of the field.
Concerns not yet addressed:
* The file-per-field version doesn't handle deleted fields
* Reportable fields will be stored in different columns/tables in different environments.  This is fine, but will make diff'ing harder
@brianbegygr @jongear
=> Generate a Single file *AND* add reportable field details to the field export

CHANGELOG.md, GuaranteedRate.Sextant/GuaranteedRate.Sextant.csproj, GuaranteedRate.Sextant/Properties/AssemblyInfo.cs, GuaranteedRate.Sextant/packages.config, LoggingTestRig/LoggingTestRig.csproj, LoggingTestRig/packages.config
* **Update** - Metrics.NET was released to stable, updating the nuget packages to reflect the change
```csharp
[GuaranteedRate.Sextant "17.2.2.2"]
```
=> Metrics.NET was released to stable, updating the nuget packages

CHANGELOG.md, GuaranteedRate.Sextant/Logging/Elasticsearch/ElasticsearchLogAppender.cs, GuaranteedRate.Sextant/Logging/Logger.cs, GuaranteedRate.Sextant/Logging/Loggly/LogglyLogAppender.cs, GuaranteedRate.Sextant/Metrics/Datadog/DatadogReporter.cs, GuaranteedRate.Sextant/Metrics/Graphite/GraphiteReporter.cs, GuaranteedRate.Sextant/Metrics/StatsDMetrics.cs, GuaranteedRate.Sextant/Properties/AssemblyInfo.cs
* **Update** - Added `Loggers.Setup()` to allow for the same configuration flow as seen in `StatsDMetrics`
[GuaranteedRate.Sextant "17.2.2.3"]
```
=> Added `Loggers.Setup()` to allow for the same configuration flow as seen with metrics

CHANGELOG.md, GuaranteedRate.Sextant/Metrics/Datadog/DatadogReporter.cs, GuaranteedRate.Sextant/Metrics/Graphite/GraphiteReporter.cs, GuaranteedRate.Sextant/Metrics/StatsDMetrics.cs, GuaranteedRate.Sextant/Properties/AssemblyInfo.cs
* **Add** - Added ability to set global tags for `StatsDMetrics`
```csharp
[GuaranteedRate.Sextant "17.2.2.4"]
```
=> Global tags for StatsD Metrics

CHANGELOG.md, GuaranteedRate.Sextant/Metrics/StatsDMetrics.cs, GuaranteedRate.Sextant/Properties/AssemblyInfo.cs
* **Add** - Added ability to add global runtime tags for `StatsDMetrics`
```csharp
[GuaranteedRate.Sextant "17.2.2.5"]
```
=> Added ability to add global runtime tags for `StatsDMetrics`

CHANGELOG.md, GuaranteedRate.Sextant/Logging/ConsoleLogAppender.cs, GuaranteedRate.Sextant/Logging/Elasticsearch/ElasticsearchLogAppender.cs, GuaranteedRate.Sextant/Logging/ILogAppender.cs, GuaranteedRate.Sextant/Logging/Logger.cs, GuaranteedRate.Sextant/Logging/Loggly/LogglyLogAppender.cs, GuaranteedRate.Sextant/Properties/AssemblyInfo.cs, LoggingTestRig/Program.cs
* **Fix** - Regression in Loggly support that was preventing logs from being searchable
* **Add** - Added ability to add runtime tags to `Logger` via `Logger.AddTag()`
```csharp
[GuaranteedRate.Sextant "17.2.2.6"]
```
=> Fix loggly searching regression and add support for global AddTag()

CHANGELOG.md, GuaranteedRate.Sextant/Logging/ConsoleLogAppender.cs, GuaranteedRate.Sextant/Logging/Elasticsearch/ElasticsearchLogAppender.cs, GuaranteedRate.Sextant/Logging/ILogAppender.cs, GuaranteedRate.Sextant/Logging/Logger.cs, GuaranteedRate.Sextant/Logging/Loggly/LogglyLogAppender.cs, GuaranteedRate.Sextant/Properties/AssemblyInfo.cs
* **Fix** - Fix regression that prevented loggers from filtering logs based on configured log level tolerance
```csharp
[GuaranteedRate.Sextant "17.2.2.7"]
```
=> make log appenders respect configured log tolerance level

CHANGELOG.md, GuaranteedRate.Sextant/Logging/ConsoleLogAppender.cs, GuaranteedRate.Sextant/Logging/Elasticsearch/ElasticsearchLogAppender.cs, GuaranteedRate.Sextant/Logging/Logger.cs, GuaranteedRate.Sextant/Logging/Loggly/LogglyLogAppender.cs, GuaranteedRate.Sextant/Properties/AssemblyInfo.cs, LoggingTestRig/Program.cs
* **Add** - Added support for automatic configuration of the `ConsoleLogAppender` when utilizing `Logger.Setup()`
```csharp
[GuaranteedRate.Sextant "17.2.2.8"]
```
=> automatic configuration of the ConsoleLogAppender

CHANGELOG.md, GuaranteedRate.Sextant/GuaranteedRate.Sextant.csproj, GuaranteedRate.Sextant/Metrics/Graphite/GraphiteReporter.cs, GuaranteedRate.Sextant/Properties/AssemblyInfo.cs, GuaranteedRate.Sextant/WebClients/AsyncEventReporter.cs, GuaranteedRate.Sextant/WebClients/SecureAsyncEventReporter.cs, GuaranteedRate.Sextant/packages.config
* **Fix** - Forcing `AsyncEventReporter` to use `WebRequest` under the hood as `HttpClient` will cause deadlocks in systems with asynchronous entry points.
```csharp
[GuaranteedRate.Sextant "17.2.2.14"]
```
=> Fix loggly

CHANGELOG.md, GuaranteedRate.Sextant/GuaranteedRate.Sextant.csproj, GuaranteedRate.Sextant/Logging/Elasticsearch/ElasticLogEvent.cs, GuaranteedRate.Sextant/Logging/Elasticsearch/ElasticsearchLogAppender.cs, GuaranteedRate.Sextant/Logging/Logger.cs, GuaranteedRate.Sextant/Properties/AssemblyInfo.cs
* **Fix** - Now sending timestamps fully in UTC format
* **Fix** - Fix `ElasticsearchLogAppender` to send timestamps in date format.  Previously we were sending dates as a string which was preventing adequate date indexing
```csharp
[GuaranteedRate.Sextant "17.2.2.16"]
```
=> Fix timestamps for elasticsearch

CHANGELOG.md, GuaranteedRate.Sextant/Logging/Elasticsearch/ElasticsearchLogAppender.cs, GuaranteedRate.Sextant/Properties/AssemblyInfo.cs
setting the elasticsearch index name equal to the logger name does bad things.
=> default index name so we don't blow up elastic

CHANGELOG.md, GuaranteedRate.Sextant/Logging/Logger.cs, GuaranteedRate.Sextant/Properties/AssemblyInfo.cs
- Fix a double logging issue
- Remove default fields in PopulateEvent from entry fields to avoid dictionary key collision.
- Make use of constants in logging critical paths.
- Use InvariantCulture for DateTime, instead of the default CurrentCulture.
=> Fix double log

CHANGELOG.md, GuaranteedRate.Sextant/EncompassUtils/LoanDataUtils.cs, GuaranteedRate.Sextant/Properties/AssemblyInfo.cs
Currently, in Polaris, there are 15 fields for every condition named like Conditio.<attribute>.<Title> were attribute is in ("AddedBy" "AllowToClear" "Category" "ClearedBy" "Description" "DateCleared" "DateAdded"
"IsCleared" "IsInternal" "IsReceived" "IsReviewed" "IsWaived" "PriorTo" "Status" "Title")
e.g. 
{….
"Condition.Description.Audit_Review_-_Required": "Audit Required- File has been selected for Audit Review.  Underwriting will submit for Audit Review to AReview@GuaranteedRate.com once all conditions have been cleared.  Please allow up to 24 hours for review.",
"Condition.DateAdded.Audit_Review_-_Required": "4/19/2018 12:00:00 AM",
….}
Unfortunately, this doesn’t include enough data to reproduce the order in which conditions are printed on in UW Approval PDF Report as implemented …
=> YBR-591: capture additional uw condition data

CHANGELOG.md, GuaranteedRate.Sextant.Tests/GuaranteedRate.Sextant.Tests.csproj, GuaranteedRate.Sextant.Tests/Logging/SextantLoggerUnitTests.cs, GuaranteedRate.Sextant.Tests/packages.config, GuaranteedRate.Sextant/GuaranteedRate.Sextant.csproj, GuaranteedRate.Sextant/Logging/ILogger.cs, GuaranteedRate.Sextant/Logging/SextantLogger.cs, GuaranteedRate.Sextant/Properties/AssemblyInfo.cs, README.md
Proposing a new `ILogger` interface and `SextantLogger` implementation for supporting standard logging and unit testing in form codebases.
[x] Unit tests pass?
[x] Version bumped?
[x] Changelog?
[x] Readme?
=> [Sextant] Proposing a new `ILogger` interface and `SextantLogger`

CHANGELOG.md, GuaranteedRate.Sextant.Tests/GuaranteedRate.Sextant.Tests.csproj, GuaranteedRate.Sextant.Tests/Logging/NullLoggerUnitTests.cs, GuaranteedRate.Sextant/GuaranteedRate.Sextant.csproj, GuaranteedRate.Sextant/Logging/NullLogger.cs, GuaranteedRate.Sextant/Properties/AssemblyInfo.cs, README.md
Based on feedback from a different code review, I added a new `NullLogger` implementation of `ILogger` to support scenarios where configuration settings aren't available.
An example use case has been added to the **Readme** file for more background.
[x] Unit tests pass?
[x] Version bumped?
[x] Changelog?
[x] Readme?
=> [NullLogger] New NullLogger implementation for ILogger interface

GuaranteedRate.Sextant.Integration.Tests/GuaranteedRate.Sextant.Integration.Tests.csproj, GuaranteedRate.Sextant.Integration.Tests/Logging/SextantLoggerIntegrationTests.cs, GuaranteedRate.Sextant.Integration.Tests/app.config, LoggingTestRig/App.config, LoggingTestRig/LoggingTestRig.csproj, LoggingTestRig/Program.cs
This is a follow up commit to the PR that @GeorgeGomez had yesterday that included the logging change in order to properly honor the Loggly configuration settings for minimum logging levels.
This commit includes the integration tests and the updates to the existing LoggingTestRig project that I updated in order to validate those changes prior to approving the previous PR.
This commit doesn't include any changes to the actual code itself, so the Assembly Version and the Changelog files were intentionally left unmodified.
=> [LOS-3593-Tests] - Integration tests and updated LoggingTestRig

CHANGELOG.md, GuaranteedRate.Sextant.Integration.Tests/EncompassUtils/SessionUtilsTests.cs, GuaranteedRate.Sextant.Integration.Tests/GuaranteedRate.Sextant.Integration.Tests.csproj, GuaranteedRate.Sextant.Integration.Tests/app.config, GuaranteedRate.Sextant/EncompassUtils/SessionUtils.cs, GuaranteedRate.Sextant/Exceptions/ServerConnectionException.cs, GuaranteedRate.Sextant/Exceptions/ServerLoginException.cs, GuaranteedRate.Sextant/GuaranteedRate.Sextant.csproj, GuaranteedRate.Sextant/Properties/AssemblyInfo.cs, LoggingTestRig/App.config
New session exceptions to help with error handling and retry logic. 
These changes are intended to make it easier to customize retry policies for things like Task Processor 3, based on the different reasons why an Encompass session could not be created.
=> [SessionRecovery] New session exceptions to help with error handling and retry logic.

CHANGELOG.md, GuaranteedRate.Examples.FieldUtils/GuaranteedRate.Examples.FieldUtils.csproj, GuaranteedRate.Examples.FieldUtils/packages.config, GuaranteedRate.Examples.LoanDataUtils/GuaranteedRate.Examples.LoanDataUtils.csproj, GuaranteedRate.Examples.LoanDataUtils/packages.config, GuaranteedRate.Examples.ReportingUtils/GuaranteedRate.Examples.ReportingUtils.csproj, GuaranteedRate.Examples.ReportingUtils/packages.config, GuaranteedRate.Examples.UserUtils/GuaranteedRate.Examples.UserUtils.csproj, GuaranteedRate.Examples.UserUtils/packages.config, GuaranteedRate.Sextant.ConsoleTester/GuaranteedRate.Sextant.ConsoleTester.csproj, GuaranteedRate.Sextant.ConsoleTester/packages.config, GuaranteedRate.Sextant.CustomFieldComparer/GuaranteedRate.Sextant.CustomFieldComparer.csproj, GuaranteedRate.Sextant.CustomFieldComparer/packages.config, GuaranteedRate.Sextant.Integration.Core/GuaranteedRate.Sextant.Integration.Core.csproj, GuaranteedRate.Sextant.Integration.Core/packages.config, GuaranteedRate.Sextant.Tests/GuaranteedRate.Sextant.Tests.csproj, GuaranteedRate.Sextant.Tests/packages.config, GuaranteedRate.Sextant/GuaranteedRate.Sextant.csproj, GuaranteedRate.Sextant/Properties/AssemblyInfo.cs, GuaranteedRate.Sextant/packages.config, GuaranteedRate.Util.IndexFields/GuaranteedRate.Util.IndexFields.csproj, GuaranteedRate.Util.IndexFields/packages.config, LoggingTestRig/LoggingTestRig.csproj, LoggingTestRig/packages.config
NuGet package updates required for supporting Elastic Search 6.0.1:
- Updated `Elasticsearch.net` to 6.0.1
- Updated `Serilog.Sinks.Elasticsearch` to 6.5.0, as required for Elastic Search 6.x
- Updated `Serilog` to 2.6.0, as required for `Serilog.Sinks.Elasticsearch`
The `.nuspec` file for Sextant should be automatically updated by the build server once these changes are merged, but I will verify that is the case before moving onto the next set of changes.
=> Elastic Search 6.0.1

CHANGELOG.md, GuaranteedRate.Sextant.Integration.Tests/GuaranteedRate.Sextant.Integration.Tests.csproj, GuaranteedRate.Sextant.Integration.Tests/packages.config, GuaranteedRate.Sextant.Tests/Logging/SextantLoggerUnitTests.cs, GuaranteedRate.Sextant/Config/JsonEncompassConfig.cs, GuaranteedRate.Sextant/Logging/ILogger.cs, GuaranteedRate.Sextant/Logging/Logger.cs, GuaranteedRate.Sextant/Logging/NullLogger.cs, GuaranteedRate.Sextant/Logging/SextantLogger.cs, GuaranteedRate.Sextant/Metrics/Graphite/GraphiteReporter.cs, GuaranteedRate.Sextant/Properties/AssemblyInfo.cs, GuaranteedRate.Sextant/WebClients/ApiException.cs, GuaranteedRate.Sextant/WebClients/AsyncEventReporter.cs, GuaranteedRate.Sextant/WebClients/AsyncWebEventReporter.cs
Adding optional support for passing in tags in a Log statement to help provide additional details for shared loggers that are injected into different workflows (i.e. tasks) that can't provide workflow related values at initialization time when `Logger.Setup()` is called.
Also, cleared up a few build warnings in the process
=> [LOS-451] Optional tags per log statement

CHANGELOG.md, GuaranteedRate.Sextant/EncompassUtils/SessionUtils.cs, GuaranteedRate.Sextant/Properties/AssemblyInfo.cs
The current error handling for the `OpenLoan()` method is to just write to the console and return `null`.
This doesn't allow us to distinguish between "Loan not found" type errors, and errors that could be related to other types of Encompass issues.
By having the option to throw an exception on error, calling methods that want to distinguish between "Loan not found" and other errors can trap and handle different types of exceptions accordingly.
All existing code calling `OpenLoan()` without the new parameter will continue to just receive `null` without an exception when a problem occurs.
=> [LOS-1955] Option to throw exception on loan open

GuaranteedRate.Sextant.Integration.Tests/app.config
We want to move off of elasticsearch.guaranteedrate.com in favor of
elasticsearch.dev.platform.rate.com and elasticsearch.platform.rate.com.
=> Update elasticsearch url
