CHANGELOG.md
GuaranteedRate.Examples.LoanDataUtils/LoanExtractor.cs
GuaranteedRate.Examples.ReportingUtils/GuaranteedRate.Examples.ReportingUtils.csproj
GuaranteedRate.Examples.ReportingUtils/Properties/AssemblyInfo.cs
GuaranteedRate.Examples.ReportingUtils/ReportingExample.cs
GuaranteedRate.Examples.ReportingUtils/packages.config
GuaranteedRate.Sextant.sln
GuaranteedRate.Sextant/EncompassUtils/LoanDataUtils.cs
GuaranteedRate.Sextant/EncompassUtils/Reporting.cs
GuaranteedRate.Sextant/Properties/AssemblyInfo.cs
README.md

This branch adds Reporting.cs based on @dkalinofski-gr / @fcorreal-gr  code for running reports.
It also adds insane amounts of error handling to prevent exceptions from crossing the DLL boundary, which seems to cause Encompass to throw deadlock exceptions
@ericsind @fcorreal-gr @dkalinofski-gr please review

Historical & Defensive Coding

---

CHANGELOG.md
GuaranteedRate.Examples.UserUtils/App.config
GuaranteedRate.Examples.UserUtils/GuaranteedRate.Examples.UserUtils.csproj
GuaranteedRate.Examples.UserUtils/Program.cs
GuaranteedRate.Examples.UserUtils/Properties/AssemblyInfo.cs
GuaranteedRate.Examples.UserUtils/packages.config
GuaranteedRate.Sextant.sln
GuaranteedRate.Sextant/EncompassUtils/UserUtils.cs
GuaranteedRate.Sextant/GuaranteedRate.Sextant.csproj
GuaranteedRate.Sextant/Models/EncompassUser.cs
GuaranteedRate.Sextant/Properties/AssemblyInfo.cs
README.md

Allows simplified functionality for acquiring user collections and
company wide user updates

Adding User Util

---

CHANGELOG.md
GuaranteedRate.Examples.LoanDataUtils/LoanExtractor.cs
GuaranteedRate.Sextant/EncompassUtils/LoanDataUtils.cs
GuaranteedRate.Sextant/Properties/AssemblyInfo.cs
GuaranteedRate.Sextant/WebClients/AsyncEventReporter.cs

This update allows for clean shutdowns by having the Shutdown() method block until the queue is drained.
Also fixed a couple of minor bugs.

Fix Shutdown

---

CHANGELOG.md
GuaranteedRate.Sextant/Properties/AssemblyInfo.cs
GuaranteedRate.Sextant/WebClients/AsyncEventReporter.cs

Bug fixes to make the extra setup work correctly

Extra setup

---

CHANGELOG.md
GuaranteedRate.Examples.LoanDataUtils/LoanExtractor.cs
GuaranteedRate.Examples.LoanDataUtils/Properties/AssemblyInfo.cs
GuaranteedRate.Sextant/EncompassUtils/FieldUtils.cs
GuaranteedRate.Sextant/EncompassUtils/LoanDataUtils.cs
GuaranteedRate.Sextant/EncompassUtils/SessionUtils.cs
GuaranteedRate.Sextant/Properties/AssemblyInfo.cs

And ability to open a loan by loan number instead of guid
@fcorreal-gr @brianbegygr @antonmos

Bugfix for identifying primary pair

---

CHANGELOG.md
GuaranteedRate.Examples.FieldUtils/GuaranteedRate.Examples.FieldUtils.csproj
GuaranteedRate.Examples.FieldUtils/packages.config
GuaranteedRate.Examples.LoanDataUtils/GuaranteedRate.Examples.LoanDataUtils.csproj
GuaranteedRate.Examples.LoanDataUtils/packages.config
GuaranteedRate.Examples.ReportingUtils/GuaranteedRate.Examples.ReportingUtils.csproj
GuaranteedRate.Examples.ReportingUtils/packages.config
GuaranteedRate.Examples.UserUtils/GuaranteedRate.Examples.UserUtils.csproj
GuaranteedRate.Examples.UserUtils/packages.config
GuaranteedRate.Sextant/Config/IEncompassConfig.cs
GuaranteedRate.Sextant/Config/IniConfig.cs
GuaranteedRate.Sextant/GuaranteedRate.Sextant.csproj
GuaranteedRate.Sextant/Loggers/Loggly.cs
GuaranteedRate.Sextant/Properties/AssemblyInfo.cs
GuaranteedRate.Sextant/packages.config
GuaranteedRate.Util.IndexFields/GuaranteedRate.Util.IndexFields.csproj
GuaranteedRate.Util.IndexFields/packages.config

@brianbegygr @MaxReznik @KseniaLaney @nhanhardtGR 
Sorry for the radio silence, been hit by a bus today.
This is an updated sextant with the Config driven logging levels and a switch from the Complete to Standard EncompassSDK.

Logging upgrades

---

CHANGELOG.md
GuaranteedRate.Sextant/EncompassUtils/LoanDataUtils.cs
GuaranteedRate.Sextant/Properties/AssemblyInfo.cs

Safe dictionary inserts

---

CHANGELOG.md
GuaranteedRate.Sextant/EncompassUtils/LoanDataUtils.cs
GuaranteedRate.Sextant/Properties/AssemblyInfo.cs

@KseniaLaney @nhanhardtGR @brianbegygr

Added funding fees to the set of data to be extracted

---

CHANGELOG.md
GuaranteedRate.Sextant/EncompassUtils/SessionUtils.cs
GuaranteedRate.Sextant/Properties/AssemblyInfo.cs

@jeffpsherman, @KseniaLaney  I'm just pulling the guid lookup into a public function.

expose loan guid search functionality.

---

CHANGELOG.md
GuaranteedRate.Sextant/Loggers/Loggly.cs
GuaranteedRate.Sextant/Properties/AssemblyInfo.cs
GuaranteedRate.Sextant/WebClients/AsyncEventReporter.cs

@nhanhardtGR @KseniaLaney @brianbegygr @normhanson

204 should be considered a successful response

---

CHANGELOG.md
GuaranteedRate.Sextant/Config/IniConfig.cs
GuaranteedRate.Sextant/Properties/AssemblyInfo.cs
GuaranteedRate.SextantTests/Config/IniConfigTests.cs
GuaranteedRate.SextantTests/GuaranteedRate.SextantTests.csproj

Allow the IniConfig to accept values that contain an equal sign

---

CHANGELOG.md
GuaranteedRate.Sextant/Config/JsonEncompassConfig.cs
GuaranteedRate.Sextant/Properties/AssemblyInfo.cs
GuaranteedRate.SextantTests/Config/JsonEncompassConfigTests.cs

This was really about ruining Brian's day.

Ruin jons day

---

CHANGELOG.md
GuaranteedRate.Sextant/Logging/Logger.cs
GuaranteedRate.Sextant/Properties/AssemblyInfo.cs

Move loggly to the end of  the reporters so we can debug problems.

make loggly log last

---

CHANGELOG.md
GuaranteedRate.Sextant/GuaranteedRate.Sextant.csproj
GuaranteedRate.Sextant/Properties/AssemblyInfo.cs
GuaranteedRate.Sextant/app.config
GuaranteedRate.Sextant/packages.config

Upgrade to Encompass SDK 17.3.   Merging into an RC branch so we can do testing on it.

upgrade to 17.3

---

CHANGELOG.md
GuaranteedRate.Sextant.Integration.Core/App.config
GuaranteedRate.Sextant.Integration.Core/GuaranteedRate.Sextant.Integration.Core.csproj
GuaranteedRate.Sextant.Integration.Core/packages.config
GuaranteedRate.Sextant.Integration.Tests/GuaranteedRate.Sextant.Integration.Tests.csproj
GuaranteedRate.Sextant.Integration.Tests/Logging/Elasticsearch/ElasticsearchLogAppenderIntegrationTests.cs
GuaranteedRate.Sextant.Integration.Tests/app.config
GuaranteedRate.Sextant.Integration.Tests/packages.config
GuaranteedRate.Sextant/Logging/Elasticsearch/ElasticsearchLogAppender.cs
GuaranteedRate.Sextant/Properties/AssemblyInfo.cs

Elasticsearch cannot handle mixed case index names so it dies horribly on log post.

Index name

---

CHANGELOG.md
GuaranteedRate.Sextant/Properties/AssemblyInfo.cs
GuaranteedRate.Sextant/WebClients/AsyncEventReporter.cs
GuaranteedRate.Sextant/WebClients/AsyncWebEventReporter.cs

Add stack trace to shutdown so we can figure out why it is firing too often.

File appender

---

CHANGELOG.md
GuaranteedRate.Examples.FieldUtils/app.config
GuaranteedRate.Examples.LoanDataUtils/LoanExtractor.cs
GuaranteedRate.Examples.LoanDataUtils/app.config
GuaranteedRate.Examples.ReportingUtils/app.config
GuaranteedRate.Examples.UserUtils/App.config
GuaranteedRate.Sextant.ConsoleTester/.gitignore
GuaranteedRate.Sextant.ConsoleTester/App.config
GuaranteedRate.Sextant.ConsoleTester/GuaranteedRate.Sextant.ConsoleTester.csproj
GuaranteedRate.Sextant.ConsoleTester/Program.cs
GuaranteedRate.Sextant.ConsoleTester/Properties/AssemblyInfo.cs
GuaranteedRate.Sextant.ConsoleTester/packages.config
GuaranteedRate.Sextant.CustomFieldComparer/App.config
GuaranteedRate.Sextant.Integration.Core/packages.config
GuaranteedRate.Sextant.Tests/app.config
GuaranteedRate.Sextant.sln
GuaranteedRate.Sextant/EncompassUtils/FieldUtils.cs
GuaranteedRate.Sextant/EncompassUtils/LoanDataUtils.cs
GuaranteedRate.Sextant/Properties/AssemblyInfo.cs
GuaranteedRate.Sextant/app.config
GuaranteedRate.Util.IndexFields/App.config
LoggingTestRig/Program.cs

Extracts the attachments and saves what data we have to a new element in metadata.

Enable extraction of some data from efolder documents

---

CHANGELOG.md
GuaranteedRate.Sextant/Logging/SimpleLogEvent.cs
GuaranteedRate.Sextant/Properties/AssemblyInfo.cs

Fix a bug where tags don't appear in Elasticsearch.

fix tags, bump

---

CHANGELOG.md
GuaranteedRate.Sextant/Logging/Logger.cs
GuaranteedRate.Sextant/Properties/AssemblyInfo.cs
README.md

Structured logs were not breaking out properties into individual fields in Loggly and Elastic.

get structured logs working

---

CHANGELOG.md
GuaranteedRate.Sextant/Logging/Logger.cs
GuaranteedRate.Sextant/Logging/SerilogHelpers.cs
GuaranteedRate.Sextant/Properties/AssemblyInfo.cs
LoggingTestRig/Program.cs

Default the index name to something that Elasticsearch likes.

Add default date index, fix whitespace, test tags in test rig.

---

CHANGELOG.md
GuaranteedRate.Sextant.Tests/packages.config
GuaranteedRate.Sextant/Properties/AssemblyInfo.cs
GuaranteedRate.Sextant/WebClients/AsyncEventReporter.cs

Apparently, TryKeep caused a severe CPU spike. I haven't looked into why, just know that it does. Could not reproduce locally.

Retry on the logic, not using TryKeep.

---

CHANGELOG.md
GuaranteedRate.Examples.FieldUtils/GuaranteedRate.Examples.FieldUtils.csproj
GuaranteedRate.Examples.FieldUtils/packages.config
GuaranteedRate.Examples.LoanDataUtils/GuaranteedRate.Examples.LoanDataUtils.csproj
GuaranteedRate.Examples.LoanDataUtils/packages.config
GuaranteedRate.Examples.ReportingUtils/GuaranteedRate.Examples.ReportingUtils.csproj
GuaranteedRate.Examples.ReportingUtils/packages.config
GuaranteedRate.Examples.UserUtils/GuaranteedRate.Examples.UserUtils.csproj
GuaranteedRate.Examples.UserUtils/packages.config
GuaranteedRate.Sextant.ConsoleTester/GuaranteedRate.Sextant.ConsoleTester.csproj
GuaranteedRate.Sextant.ConsoleTester/packages.config
GuaranteedRate.Sextant.Integration.Core/GuaranteedRate.Sextant.Integration.Core.csproj
GuaranteedRate.Sextant.Integration.Core/packages.config
GuaranteedRate.Sextant.Tests/GuaranteedRate.Sextant.Tests.csproj
GuaranteedRate.Sextant.Tests/packages.config
GuaranteedRate.Sextant/GuaranteedRate.Sextant.csproj
GuaranteedRate.Sextant/Properties/AssemblyInfo.cs
GuaranteedRate.Sextant/packages.config
GuaranteedRate.Util.IndexFields/GuaranteedRate.Util.IndexFields.csproj
GuaranteedRate.Util.IndexFields/packages.config
LoggingTestRig/LoggingTestRig.csproj
LoggingTestRig/packages.config

Update to EncompassSDK.Complete package version 19.1

---

CHANGELOG.md
GuaranteedRate.Examples.FieldUtils/GuaranteedRate.Examples.FieldUtils.csproj
GuaranteedRate.Examples.FieldUtils/packages.config
GuaranteedRate.Examples.LoanDataUtils/GuaranteedRate.Examples.LoanDataUtils.csproj
GuaranteedRate.Examples.LoanDataUtils/packages.config
GuaranteedRate.Examples.ReportingUtils/GuaranteedRate.Examples.ReportingUtils.csproj
GuaranteedRate.Examples.ReportingUtils/packages.config
GuaranteedRate.Examples.UserUtils/GuaranteedRate.Examples.UserUtils.csproj
GuaranteedRate.Examples.UserUtils/packages.config
GuaranteedRate.Sextant.ConsoleTester/GuaranteedRate.Sextant.ConsoleTester.csproj
GuaranteedRate.Sextant.ConsoleTester/packages.config
GuaranteedRate.Sextant.Integration.Core/GuaranteedRate.Sextant.Integration.Core.csproj
GuaranteedRate.Sextant.Integration.Core/packages.config
GuaranteedRate.Sextant.Tests/GuaranteedRate.Sextant.Tests.csproj
GuaranteedRate.Sextant.Tests/packages.config
GuaranteedRate.Sextant/GuaranteedRate.Sextant.csproj
GuaranteedRate.Sextant/Properties/AssemblyInfo.cs
GuaranteedRate.Sextant/packages.config
GuaranteedRate.Util.IndexFields/GuaranteedRate.Util.IndexFields.csproj
GuaranteedRate.Util.IndexFields/packages.config
LoggingTestRig/LoggingTestRig.csproj
LoggingTestRig/packages.config

Updating to use newest EncompassSDK.Complete version

---

CHANGELOG.md
GuaranteedRate.Sextant/EncompassUtils/EncompassInit.cs
GuaranteedRate.Sextant/GuaranteedRate.Sextant.csproj
GuaranteedRate.Sextant/Properties/AssemblyInfo.cs
GuaranteedRate.Sextant/packages.config

Removed dependency on EncompassSDK.Complete NuGet package as well as other unnecessary dependencies.

Emp-160 Removed dependency on unnecessary packages

---

CHANGELOG.md
GuaranteedRate.Examples.FieldUtils/GuaranteedRate.Examples.FieldUtils.csproj
GuaranteedRate.Examples.FieldUtils/packages.config
GuaranteedRate.Examples.LoanDataUtils/GuaranteedRate.Examples.LoanDataUtils.csproj
GuaranteedRate.Examples.LoanDataUtils/packages.config
GuaranteedRate.Examples.ReportingUtils/GuaranteedRate.Examples.ReportingUtils.csproj
GuaranteedRate.Examples.ReportingUtils/packages.config
GuaranteedRate.Examples.UserUtils/GuaranteedRate.Examples.UserUtils.csproj
GuaranteedRate.Examples.UserUtils/packages.config
GuaranteedRate.Sextant.ConsoleTester/GuaranteedRate.Sextant.ConsoleTester.csproj
GuaranteedRate.Sextant.ConsoleTester/packages.config
GuaranteedRate.Sextant.Integration.Core/GuaranteedRate.Sextant.Integration.Core.csproj
GuaranteedRate.Sextant.Integration.Core/packages.config
GuaranteedRate.Sextant.Integration.Tests/GuaranteedRate.Sextant.Integration.Tests.csproj
GuaranteedRate.Sextant.Integration.Tests/packages.config
GuaranteedRate.Sextant.Tests/GuaranteedRate.Sextant.Tests.csproj
GuaranteedRate.Sextant.Tests/packages.config
GuaranteedRate.Sextant/GuaranteedRate.Sextant.csproj
GuaranteedRate.Util.IndexFields/GuaranteedRate.Util.IndexFields.csproj
GuaranteedRate.Util.IndexFields/packages.config

EMP-597 Update to Encompass SDK 20.1

EMP-597 Update to Encompass SDK 20.1

---

CHANGELOG.md
GuaranteedRate.Sextant.Integration.Core/IntegrationEncompassConfig.cs
GuaranteedRate.Sextant.Integration.Tests/EncompassSDKBaseTest.cs
GuaranteedRate.Sextant.Integration.Tests/EncompassUtils/SessionUtilsTests.cs
GuaranteedRate.Sextant.Integration.Tests/GuaranteedRate.Sextant.Integration.Tests.csproj
GuaranteedRate.Sextant.Integration.Tests/Logging/LogIntegrationTests.cs
GuaranteedRate.Sextant.Integration.Tests/Logging/SeriLoggerIntegrationTests.cs
GuaranteedRate.Sextant.Integration.Tests/Logging/SextantLoggerIntegrationTests.cs
GuaranteedRate.Sextant.Integration.Tests/Metrics/Datadog/DatadogReporterIntegrationTests.cs
GuaranteedRate.Sextant.Integration.Tests/Metrics/Graphite/GraphiteReporterIntegrationTests.cs
GuaranteedRate.Sextant.Integration.Tests/app.config
GuaranteedRate.Sextant.Tests/Configs/JsonEncompassConfigTests.cs
GuaranteedRate.Sextant.Tests/Configs/TestIni.ini
GuaranteedRate.Sextant.Tests/Configs/TestJson.json
GuaranteedRate.Sextant.Tests/EncompassSDKBaseTest.cs
GuaranteedRate.Sextant.Tests/GuaranteedRate.Sextant.Tests.csproj
GuaranteedRate.Sextant.Tests/Logging/SeriLoggerUnitTests.cs
GuaranteedRate.Sextant.Tests/Logging/SextantLoggerUnitTests.cs
GuaranteedRate.Sextant.Tests/packages.config
GuaranteedRate.Sextant/Config/IEncompassConfig.cs
GuaranteedRate.Sextant/Config/IJsonEncompassConfig.cs
GuaranteedRate.Sextant/Config/IniConfig.cs
GuaranteedRate.Sextant/Config/JsonEncompassConfig.cs
GuaranteedRate.Sextant/GuaranteedRate.Sextant.csproj
GuaranteedRate.Sextant/Logging/SeriLogger.cs

LOSKV-48: Add basic orgId config switching.
EMP-825: Change logging format.
Fix Integration Tests.

LOSJV-48 & EMP-825
